version: '3.9'

services:
  db-investiment:
    container_name: db-investiment
    image: mysql:8.1.0
    restart: always
    env_file:
      - api/.env
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - 3306:3306
    command: ["--event-scheduler=ON"]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 10
    networks:
      - database-network-investiment

  api-investiment:
    build: . 
    container_name: api-investiment
    restart: always
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      db-investiment:
        condition: service_healthy
    networks:
      - database-network-investiment

networks:
  database-network-investiment:
      driver: bridge    